name: practicing the git hub
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v6  
  installing java: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v6
        with: 
          java-version: 21
          disturbution: 'temurin'
          

    